# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    git config --global user.email "azure.devops@azure.com"
    git config --global user.name "Azure DevOps"
    git config --global credential.helper 'store --stdin'
    git remote set-url origin https://$(GITHUB_PAT)@github.comgithub.com/VictorBejarano/victorbejarano.github.io.git
    git checkout .
    git fetch origin
    git checkout master
  displayName: Checkout repository

- script: |
    curl -sL https://deb.nodesource.com/setup_20.x | bash -s
    sudo apt-get install -y nodejs
    sudo npm install -g nx@18.3.4
    node -v
    npm -v
  displayName: Setup Node.js

- script: |
    npm install
  displayName: Install Nx dependencies

- script: |
    nx build portfolio --prod
  displayName: Build Angular application
  
- script: |
    git checkout gh-pages
    rm -r ./docs
    mkdir docs
    mv ./dist/apps/portfolio/browser/* ./docs
    git add ./docs
    git status
    git commit -m "Despliege Azure"
    git push origin gh-pages --force
  displayName: Publish to Github Pages